In [2]:
import sys
import os
from pathlib import Path

current_dir = os.getcwd()
src_dir = os.path.abspath(os.path.join(current_dir, '..'))

if src_dir not in sys.path:
    sys.path.append(src_dir)

In [3]:
import pandas as pd
from src.utils.config_loader import config_loader
from src.preprocessing.feature_engineer import FeatureEngineer

ROOTPATH = Path.cwd().parent
DATA_PATHS = config_loader.get_data_paths()
PROCESSED_DATA_PATH = ROOTPATH / DATA_PATHS['processed_data_path']
FEATURE_PATH = ROOTPATH / DATA_PATHS['features_data_path']

In [4]:
df = pd.read_parquet(PROCESSED_DATA_PATH / 'preprocessed.parquet')

In [5]:
fe = FeatureEngineer()

2025-06-22 22:20:40,664 - src.preprocessing.feature_engineer - INFO - FeatureEngineer initialized with session timeout: 30 minutes

In [5]:
# Step 1: Session IDs
df = fe.generate_and_save_session_ids(df, f'{FEATURE_PATH}/with_sessions.parquet')

2025-06-22 21:23:19,512 - src.preprocessing.feature_engineer - INFO - Generating and saving session IDs to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/with_sessions.parquet
2025-06-22 21:23:19,513 - src.preprocessing.feature_engineer - INFO - Creating session ids...
2025-06-22 21:24:44,178 - src.preprocessing.feature_engineer - INFO - Session ids created successfully. Found 16355807 unique sessions
2025-06-22 21:25:09,711 - src.preprocessing.feature_engineer - INFO - Saved features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/with_sessions.parquet. Shape: (98914533, 10)

In [6]:
# Step 2: User features
fe.generate_and_save_user_features(df, f'{FEATURE_PATH}/user_features.parquet')

2025-06-22 21:25:10,962 - src.preprocessing.feature_engineer - INFO - Generating and saving user features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/user_features.parquet
2025-06-22 21:25:10,963 - src.preprocessing.feature_engineer - INFO - Creating user features...
2025-06-22 21:26:44,458 - src.preprocessing.feature_engineer - INFO - User features created successfully. Shape: (987984, 17)
2025-06-22 21:26:44,706 - src.preprocessing.feature_engineer - INFO - Saved features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/user_features.parquet. Shape: (987984, 17)

,user_id,total_actions,first_action,last_action,unique_items_viewed,unique_categories_viewed,num_sessions,user_pv_count,user_fav_count,user_cart_count,user_buy_count,account_age_days,cart_to_buy_ratio,fav_to_buy_ratio,view_to_buy_ratio,actions_per_day,unique_items_per_session
0,1,53,2017-11-25 01:21:25,2017-12-03 06:17:27,44,20,46,53.0,0.0,0.0,0.0,8.205579,0.000000,0.0,0.000000,6.459020,0.956522
1,2,71,2017-11-25 14:11:15,2017-12-03 14:43:30,50,30,17,54.0,7.0,3.0,7.0,8.022396,2.333333,1.0,0.129630,8.850224,2.941176
2,3,53,2017-11-25 05:16:40,2017-12-03 11:16:36,50,33,24,33.0,5.0,15.0,0.0,8.249954,0.000000,0.0,0.000000,6.424278,2.083333
3,4,285,2017-11-25 13:38:55,2017-12-03 11:54:06,184,23,24,268.0,0.0,13.0,4.0,7.927211,0.307692,0.0,0.014925,35.952116,7.666667
4,5,64,2017-11-26 02:26:30,2017-12-02 11:24:50,58,29,8,64.0,0.0,0.0,0.0,6.373843,0.000000,0.0,0.000000,10.041039,7.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987979,1018007,162,2017-11-25 12:07:32,2017-12-03 10:56:18,129,29,16,161.0,1.0,0.0,0.0,7.950532,0.000000,0.0,0.000000,20.375994,8.062500
987980,1018008,49,2017-11-25 05:35:03,2017-12-03 01:46:01,40,12,8,32.0,17.0,0.0,0.0,7.840949,0.000000,0.0,0.000000,6.249243,5.000000
987981,1018009,311,2017-11-25 10:26:37,2017-12-03 14:31:15,236,52,23,286.0,2.0,21.0,2.0,8.169884,0.095238,1.0,0.006993,38.066635,10.260870
987982,1018010,80,2017-11-25 14:13:45,2017-12-03 05:58:40,61,20,15,72.0,0.0,2.0,6.0,7.656192,3.000000,0.0,0.083333,10.449059,4.066667
987983,1018011,42,2017-11-25 02:17:03,2017-12-03 05:57:34,29,10,10,41.0,0.0,0.0,1.0,8.153137,0.000000,0.0,0.024390,5.151392,2.900000

In [7]:
# Step 3: Item features
fe.generate_and_save_item_features(df, f'{FEATURE_PATH}/item_features.parquet')

2025-06-22 21:26:44,731 - src.preprocessing.feature_engineer - INFO - Generating and saving item features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/item_features.parquet
2025-06-22 21:26:44,732 - src.preprocessing.feature_engineer - INFO - Creating item features...
2025-06-22 21:31:21,604 - src.preprocessing.feature_engineer - INFO - Item features created successfully. Shape: (4142583, 11)
2025-06-22 21:31:22,163 - src.preprocessing.feature_engineer - INFO - Saved features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/item_features.parquet. Shape: (4142583, 11)

,item_id,total_views,unique_viewers,pv_count,fav_count,cart_count,buy_count,view_to_cart_rate,cart_to_buy_rate,view_to_buy_rate,popularity_score
0,1,2,1,2.0,0.0,0.0,0.0,0.0000,0.0,0.000000,2.0
1,3,2,2,2.0,0.0,0.0,0.0,0.0000,0.0,0.000000,2.0
2,4,3,2,3.0,0.0,0.0,0.0,0.0000,0.0,0.000000,3.0
3,5,2,2,2.0,0.0,0.0,0.0,0.0000,0.0,0.000000,2.0
4,6,1,1,1.0,0.0,0.0,0.0,0.0000,0.0,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...
4142578,5163065,2,2,2.0,0.0,0.0,0.0,0.0000,0.0,0.000000,2.0
4142579,5163067,17,17,16.0,0.0,1.0,0.0,0.0625,0.0,0.000000,19.0
4142580,5163068,4,4,3.0,0.0,0.0,1.0,0.0000,0.0,0.333333,7.0
4142581,5163069,1,1,1.0,0.0,0.0,0.0,0.0000,0.0,0.000000,1.0
4142582,5163070,1,1,1.0,0.0,0.0,0.0,0.0000,0.0,0.000000,1.0

In [8]:
# Step 4: Category features
fe.generate_and_save_category_features(df, f'{FEATURE_PATH}/category_features.parquet')

2025-06-22 21:31:22,174 - src.preprocessing.feature_engineer - INFO - Generating and saving category features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/category_features.parquet
2025-06-22 21:31:22,176 - src.preprocessing.feature_engineer - INFO - Creating category features...
2025-06-22 21:31:35,733 - src.preprocessing.feature_engineer - INFO - Category features created successfully. Shape: (9435, 10)
2025-06-22 21:31:35,739 - src.preprocessing.feature_engineer - INFO - Saved features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/category_features.parquet. Shape: (9435, 10)

,category_id,category_total_views,category_unique_viewers,category_unique_items,category_pv_count,category_fav_count,category_cart_count,category_buy_count,category_conversion_rate,category_popularity
0,80,20,12,10,20.0,0.0,0.0,0.0,0.000000,20
1,1147,1,1,1,1.0,0.0,0.0,0.0,0.000000,1
2,2171,1819,792,242,1519.0,43.0,156.0,101.0,0.066447,1819
3,2410,717,430,99,650.0,17.0,36.0,14.0,0.021505,717
4,2424,49,3,9,44.0,0.0,1.0,4.0,0.088889,49
...,...,...,...,...,...,...,...,...,...,...
9430,5159111,12,11,4,12.0,0.0,0.0,0.0,0.000000,12
9431,5159987,3,2,2,3.0,0.0,0.0,0.0,0.000000,3
9432,5160054,207,58,17,196.0,0.0,3.0,8.0,0.040609,207
9433,5161669,1208,475,111,931.0,19.0,117.0,141.0,0.151288,1208
9434,5162429,2,1,1,2.0,0.0,0.0,0.0,0.000000,2

In [9]:
# Step 5: Session features
fe.generate_and_save_session_features(df, f'{FEATURE_PATH}/session_features.parquet')

2025-06-22 21:31:35,748 - src.preprocessing.feature_engineer - INFO - Generating and saving session features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/session_features.parquet
2025-06-22 21:31:35,750 - src.preprocessing.feature_engineer - INFO - Creating session features...
2025-06-22 21:58:27,050 - src.preprocessing.feature_engineer - INFO - Session features created successfully. Shape: (16355807, 9)
2025-06-22 21:58:35,848 - src.preprocessing.feature_engineer - INFO - Saved features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/session_features.parquet. Shape: (16355807, 9)

,user_id,session_id,actions_count,session_duration,unique_items,unique_categories,behavior_counts,session_duration_minutes,actions_per_minute
0,1,1_0,1,0.0,1,1,{'pv': 1},0.000000,0.000000
1,1,1_1,1,0.0,1,1,{'pv': 1},0.000000,0.000000
2,1,1_10,1,0.0,1,1,{'pv': 1},0.000000,0.000000
3,1,1_11,1,0.0,1,1,{'pv': 1},0.000000,0.000000
4,1,1_12,1,0.0,1,1,{'pv': 1},0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
16355802,1018011,1018011_5,1,0.0,1,1,{'pv': 1},0.000000,0.000000
16355803,1018011,1018011_6,1,0.0,1,1,{'pv': 1},0.000000,0.000000
16355804,1018011,1018011_7,5,665.0,3,1,{'pv': 5},11.083333,0.451128
16355805,1018011,1018011_8,8,413.0,7,1,{'pv': 8},6.883333,1.162228
16355806,1018011,1018011_9,8,1045.0,7,1,{'pv': 8},17.416667,0.459330

In [ ]:
# Step 6: Time features
fe.generate_and_save_time_features(df, f'{FEATURE_PATH}/time_features.parquet')

2025-06-22 21:58:35,862 - src.preprocessing.feature_engineer - INFO - Generating and saving time features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/time_features.parquet
2025-06-22 21:58:35,863 - src.preprocessing.feature_engineer - INFO - Creating time features...
2025-06-22 21:58:50,447 - src.preprocessing.feature_engineer - INFO - Time features created successfully. Shape: (98914533, 5)
2025-06-22 21:58:56,937 - src.preprocessing.feature_engineer - INFO - Saved features to /Users/adamchiu/Library/CloudStorage/Dropbox/Programming/Macbook/Portfolio/ML Pipeline/ecomm_purchase_propensity/data/features/time_features.parquet. Shape: (98914533, 5)

,hour,day_of_week,is_weekend,time_since_last_action,time_since_last_purchase
0,1,5,1,0.0,0.0
1,7,5,1,20608.0,0.0
2,7,5,1,2653.0,0.0
3,13,5,1,20335.0,0.0
4,21,5,1,28461.0,0.0
...,...,...,...,...,...
98914528,5,6,1,100.0,0.0
98914529,5,6,1,344.0,0.0
98914530,5,6,1,65.0,0.0
98914531,5,6,1,251.0,0.0
98914532,5,6,1,131.0,0.0

:

In [ ]:
# Step 7: Merge all features
fe.merge_all_features(
    base_df_path=f'{FEATURE_PATH}/with_sessions.parquet',
    user_features_path=f'{FEATURE_PATH}/user_features.parquet',
    item_features_path=f'{FEATURE_PATH}/item_features.parquet',
    category_features_path=f'{FEATURE_PATH}/category_features.parquet',
    session_features_path=f'{FEATURE_PATH}/session_features.parquet',
    time_features_path=f'{FEATURE_PATH}/time_features.parquet',
    output_path=f'{FEATURE_PATH}/all_features.parquet'
)

# Target Engineering

In [4]:
from src.preprocessing.target_engineer import target_engineer

2025-06-25 00:39:41,611 - src.preprocessing.target_engineer - INFO - TargetEngineer instantiated...

In [ ]:
df = pd.read_parquet(f'{FEATURE_PATH}/all_features.parquet')

In [ ]:
df_with_target = target_engineer(
    df=df,
    prediction_window_hours=24,
    method='next_session',
    preparing_modeling_dataset=True,
    remove_future_data=True
)